### ISSUE TITLE
Conda yml file

### ISSUE THREAD

**Issue by shivupa** [shivupa/QMMM_study_group#3]
Can 
- a conda yml file for requirements be created
- a txt file with instructions on how to use it

**Comment by shivupa** [comment]
@dlf57 can you do this one

**Comment by dlf57** [comment]
Yeah, I can take care of this. I can set up a simple yml that creates a separate environment for the work we do so that it does not conflict with anyone's base environment. Instead of a text file with instructions how about a short blurb in the readme with instructions on how to download anaconda if you don't have it already and then how to:
 ```conda env create -f qmmm_environment.yml```

**Comment by shivupa** [comment]
Yeah that sounds perfect! Thanks.

**Comment by shivupa** [comment]
When you make the yml file just edit the readme and submit the pull request for both please

**Comment by dlf57** [comment]
This should be fixed with #6 and can be closed now
